### ISSUE TITLE
I get a Python Error in Blender when hitting Export

### ISSUE THREAD

**Issue by oliverban** [Limbicnation/blender2houdini-exporter#7]
Hi there!
Thanks for making this but I seem to have a problem when trying to export an animated character from Blender to Houdini. Installing the Add-on and the HDA worked nicely but when selecting my dude and hitting Export it does nothing, if I don't select anything because I want the whole scene it gives me Python error. Then nothing happens at all.

Using Blender 2.6 and Houdini 20

<img width="547" alt="blender_DjUYtfnp3f" src="https://github.com/Limbicnation/blender2houdini-exporter/assets/55516443/72b15429-71bd-4579-9029-ed445a1083c2">

**Comment by Limbicnation** [comment]
Hello @oliverban  and thank you for your interest in this project! My apologies for the delayed response. As this is a side project for me, my available time to dedicate to its maintenance is limited.

To address your issue, please update your local repository or download and reinstall the latest update from here:
![blender2houdini-exporter-Addon](https://github.com/Limbicnation/blender2houdini-exporter/assets/6284675/93ffe249-a3f2-4ae3-9d2f-db59d51a58cb)

![reload-import-model](https://github.com/Limbicnation/blender2houdini-exporter/assets/6284675/92f8c473-216c-4c3b-b2c5-606b847c1d77)


It's important to ensure that all your paths are correctly configured. Thank you for your understanding and support!

**Comment by oliverban** [comment]
> Hello @oliverban and thank you for your interest in this project! My apologies for the delayed response. As this is a side project for me, my available time to dedicate to its maintenance is limited.
> 
> To address your issue, please update your local repository or download and reinstall the latest update from here: ![blender2houdini-exporter-Addon](https://private-user-images.githubusercontent.com/6284675/318881883-93ffe249-a3f2-4ae3-9d2f-db59d51a58cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNDUyNTIsIm5iZiI6MTcxMjI0NDk1MiwicGF0aCI6Ii82Mjg0Njc1LzMxODg4MTg4My05M2ZmZTI0OS1hM2YyLTRhZTMtOWQyZi1kYjU5ZDUxYTU4Y2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDRUMTUzNTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTY2MjJlMDdmOTY1MjBhY2QwMzlkNDZiNmFmZmY1ZDRhZTVmMzQ4ZWQyODVkZDg5MmZiYjI4ODZjODIyZTVkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.guL5gycY-N-TER5oqspJ2Hedr2gfjG6y-56-_enuAPM)
> 
> ![reload-import-model](https://private-user-images.githubusercontent.com/6284675/318882599-92f8c473-216c-4c3b-b2c5-606b847c1d77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNDUyNTIsIm5iZiI6MTcxMjI0NDk1MiwicGF0aCI6Ii82Mjg0Njc1LzMxODg4MjU5OS05MmY4YzQ3My0yMTZjLTRjM2ItYjJjNS02MDZiODQ3YzFkNzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDRUMTUzNTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjQzYTdlZGU5Mjk0NmUwYzZiYmYxN2M5NGUxZjY2NDhlNWJhZDkyNzYxMDI1YmMyMjFmMGQ4OGI0NmUyZWQxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BJhtu4GK2rdOmujgR1djEJyXiroBIp4D57zdRGfv8Qg)
> 
> It's important to ensure that all your paths are correctly configured. Thank you for your understanding and support!

No worries! I understand your time is limited and thanks for the respose! I'll try it again and see if it works this time!

**Comment by Limbicnation** [comment]
> > Hello @oliverban and thank you for your interest in this project! My apologies for the delayed response. As this is a side project for me, my available time to dedicate to its maintenance is limited.
> > To address your issue, please update your local repository or download and reinstall the latest update from here: ![blender2houdini-exporter-Addon](https://private-user-images.githubusercontent.com/6284675/318881883-93ffe249-a3f2-4ae3-9d2f-db59d51a58cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNDUyNTIsIm5iZiI6MTcxMjI0NDk1MiwicGF0aCI6Ii82Mjg0Njc1LzMxODg4MTg4My05M2ZmZTI0OS1hM2YyLTRhZTMtOWQyZi1kYjU5ZDUxYTU4Y2IucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDRUMTUzNTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTY2MjJlMDdmOTY1MjBhY2QwMzlkNDZiNmFmZmY1ZDRhZTVmMzQ4ZWQyODVkZDg5MmZiYjI4ODZjODIyZTVkZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.guL5gycY-N-TER5oqspJ2Hedr2gfjG6y-56-_enuAPM)
> > ![reload-import-model](https://private-user-images.githubusercontent.com/6284675/318882599-92f8c473-216c-4c3b-b2c5-606b847c1d77.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNDUyNTIsIm5iZiI6MTcxMjI0NDk1MiwicGF0aCI6Ii82Mjg0Njc1LzMxODg4MjU5OS05MmY4YzQ3My0yMTZjLTRjM2ItYjJjNS02MDZiODQ3YzFkNzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MDRUMTUzNTUyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjQzYTdlZGU5Mjk0NmUwYzZiYmYxN2M5NGUxZjY2NDhlNWJhZDkyNzYxMDI1YmMyMjFmMGQ4OGI0NmUyZWQxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BJhtu4GK2rdOmujgR1djEJyXiroBIp4D57zdRGfv8Qg)
> > It's important to ensure that all your paths are correctly configured. Thank you for your understanding and support!
> 
> No worries! I understand your time is limited and thanks for the respose! I'll try it again and see if it works this time!

Thanks for your patience and understanding! Give it another shot and let me know if you need any help. Cheers!

Best regards,
Gero
